[Desktop Entry]
Comment=An easy to use bible study tool
Comment[C]=An easy to use bible study tool
Comment[cs]=Snadno pouiteln nï¿½troj pro studium Bible
Comment[da]=Et letanvendeligt bibelstudieprogram
Comment[de]=Ein einfach zu benutzendes Bibelprogramm
Comment[fr]=Un outil d'étude biblique facile à utiliser
Exec=bibletime
Icon=bibletime
MimeType=
Name=BibleTime ${BT_VERSION}
Name[C]=BibleTime ${BT_VERSION}
Name[cs]=BibleTime ${BT_VERSION}
Name[da]=Bibletime ${BT_VERSION}
Name[de]=BibleTime ${BT_VERSION}
Name[fr]=BibleTime ${BT_VERSION}
GenericName=Bible Study Tool
Terminal=false
Type=Application
X-KDE-SubstituteUID=false
X-KDE-Username=
Categories=X-Bible;X-Religion;Literature;Art;Education;Utility;KDE;Qt;
DocPath=bibletime/handbook/index.html
