#!/bin/sh
#
# This script can be used to generate the BibleTime User Interface (UI)
# translation. It requires the installation of Qt Linguist 4.x,
# http://qt.nokia.com/doc/4.4/linguist-manual.html
#
# Author: Thomas Abthorpe <tabthorpe@FreeBSD.org>
# $LastChangedDate$
#
#set -x

OBSFLAG="-no-obsolete" # strip obsolete translations
OBSFLAG=""

_lupdatecmd="lupdate"
_lreleasecmd="lrelease"

if test $OSTYPE = FreeBSD
then
   _lupdatecmd="lupdate-qt4"
   _lreleasecmd="lrelease-qt4"
fi

cd  `dirname $0`/../../..

for _uitsfile in ./i18n/messages/bibletime_ui*.ts
do
   ${_lupdatecmd} ${OBSFLAG} ./src -ts ${_uitsfile}
done

cd ./i18n/messages/

for _uitsfile in *.ts
do
  if [ ${_uitsfile} = "bibletime_ui.ts" ]; then continue; fi

  ${_lreleasecmd} -compress ${_uitsfile}
done
