[Desktop Entry]
Comment=An easy to use bible study tool
Comment[C]=An easy to use bible study tool
Comment[cs]=Snadno použitelný nástroj pro studium Bible
Comment[da]=Et letanvendeligt bibelstudieprogram
Comment[de]=Ein einfach zu benutzendes Bibelprogramm
Comment[et]=Lihtne Piibliuurimise vahend
Comment[fi]=Helppokäyttöinen raamatunlukuohjelmisto
Comment[fr]=Un outil d'étude biblique facile à utiliser
Comment[it]=Un semplice strumento per studiare la Bibbia
Exec=bibletime
Icon=info.bibletime.BibleTime
Name=BibleTime @PROJECT_VERSION@
Name[C]=BibleTime @PROJECT_VERSION@
Name[cs]=BibleTime @PROJECT_VERSION@
Name[da]=BibleTime @PROJECT_VERSION@
Name[de]=BibleTime @PROJECT_VERSION@
Name[et]=BibleTime @PROJECT_VERSION@
Name[fr]=BibleTime @PROJECT_VERSION@
Name[it]=BibleTime @PROJECT_VERSION@
GenericName=Bible Study Tool
Terminal=false
Type=Application
Categories=X-Bible;X-Religion;Literature;Education;Dictionary;Qt;
Keywords=bible;study;religion;literature;education;
DocPath=bibletime/handbook/index.html
