INCLUDE(CheckCXXCompilerFlag)

FUNCTION(BtAddCxxCompilerFlags target)
    FOREACH(arg IN LISTS ARGN)
        IF ("${arg}" MATCHES "^-")
            STRING(SUBSTRING "${arg}" 1 -1 FlagName)
            STRING(REPLACE "+" "--plus--" FlagName "${FlagName}")
            CHECK_CXX_COMPILER_FLAG("${arg}"
                                    "cxx_compiler_has_flag_${FlagName}")
            IF("${cxx_compiler_has_flag_${FlagName}}")
                TARGET_COMPILE_OPTIONS("${target}" PUBLIC "${arg}")
            ENDIF()
        ELSE()
            MESSAGE(FATAL_ERROR "Unsupported argument: ${arg}")
        ENDIF()
    ENDFOREACH()
ENDFUNCTION()
