name: Generate and publish docs

on:
  push:
    tags:
      - v[0-9]+.**
  workflow_dispatch:
    inputs:
      tag:
        description: 'The tag for which to (re-)generate the documentation for.'
        type: string
        required: false

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
      with:
        ref: refs/tags/${{ inputs.tag || github.ref_name }}
        path: code
    - uses: actions/checkout@v6
      with:
        path: ci
        sparse-checkout: |
          .github/workflows
    - name: Gather system information
      run: |
        mkdir -p "${HOME}/info"
        cd "${HOME}/info"
        echo 2 > num_threads
    - name: Install required packages
      run: |
        sudo apt-get update
        sudo apt-get install --no-install-recommends cmake make po4a xsltproc docbook-xml docbook-xsl fop
    - name: Configure, generate and install the documentation
      run: |
        mkdir -p install build
        cd build
        cmake -DBUILD_BIBLETIME=NO -DCMAKE_INSTALL_PREFIX=../install/ ../code
        make "-j$(cat "${HOME}/info/num_threads")"
        make "-j$(cat "${HOME}/info/num_threads")" install
    - uses: actions/checkout@v6
      with:
        repository: bibletime/generated_docs
        path: generated_docs
        fetch-depth: 0
        token: ${{ secrets.GENERATED_DOCS_RW }}
    - name: Configure generated documentation repository copy
      working-directory: generated_docs
      run: |
        git config --worktree user.name 'GitHub workflow'
        git config --worktree user.email 'invalid@invalid'
    - name: Add, commit and push the generated documentation
      working-directory: generated_docs
      environment:
        SHORTREF: ${{ inputs.tag || github.ref_name }}
      run: |
        EMPTY=""
        git rm -rf --ignore-unmatch "docs/${SHORTREF}"
        mkdir -p "docs/${SHORTREF}"
        mv ../install/share/doc/BibleTime/{handbook,howto} "docs/${SHORTREF}/"
        git add "docs/${SHORTREF}"
        ../ci/.github/workflows/generate_docs_index.sh > docs/index.html
        git add docs/index.html
        cat << EOF > commitMessage
        Automatic GitHub ${GITHUB_EVENT_NAME:-workflow} update for ${SHORTREF}
        $EMPTY
        GITHUB_REPOSITORY: ${GITHUB_REPOSITORY}
        GITHUB_REF: ${GITHUB_REF}
        GITHUB_SHA: ${GITHUB_SHA}
        GITHUB_ACTOR: ${GITHUB_ACTOR}
        $EMPTY
        GITHUB_RUN_ID: ${GITHUB_RUN_ID}
        GITHUB_RUN_NUMBER: ${GITHUB_RUN_NUMBER}
        GITHUB_ACTION: ${GITHUB_ACTION}
        EOF
        git commit -F commitMessage
        git push
